In [1]:
import numpy as np

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [2]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")

Python list size: 8056000 bytes


In [6]:
arr = np.array([1, 2, 3], dtype=np.float32) # Explicit type
print(arr.dtype) # float32


arr_int = arr.astype(np.int32) # Convert float to int
print(arr_int) # [1 2 3]

float32
[1 2 3]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape) # (2, 3)


reshaped = arr.reshape((3, 2)) # Change shape
print(reshaped)
# [[1 2]
# [3 4]
# [5 6]]


flattened = arr.flatten() # Convert 2D → 1D
print(flattened) # [1 2 3 4 5 6]

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [8]:
arr = np.array([10, 20, 30, 40, 50])


print(arr[1:4]) # [20 30 40] (slice from index 1 to 3)

print(arr[:3]) # [10 20 30] (first 3 elements)

print(arr[::2]) # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [9]:
arr = np.array([10, 20, 30, 40, 50])

idx = [0, 2, 4] # Indices to select


print(arr[idx]) # [10 30 50]


[10 30 50]


In [10]:
arr = np.array([10, 20, 30, 40, 50])

mask = arr > 25 # Condition: values greater than 25


print(arr[mask]) # [30 40 50]

[30 40 50]


In [11]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
[[7, 8, 9], [10, 11, 12]]])


# Output of arr3D.shape is → (depth, rows, columns)

print(arr3D.shape) # Output: (2, 2, 3)


(2, 2, 3)


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
result = []

# Using a loop to square each element (slow)
for num in arr:
 result.append(num ** 2)

print(result)

[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [15]:
arr = np.array([1, 2, 3, 4, 5])

result = arr ** 2 # Vectorized operation

print(result)

[ 1  4  9 16 25]


In [16]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

arr2 = np.array([1, 2, 3])

result = arr1 + arr2 # Broadcasting arr2 across arr1
print(result)

[[2 4 6]
 [5 7 9]]
